### PR TITLE
Extend the application-layer API to avoid hard-coded protocol-related constants in applications

### PR DESCRIPTION
**Pull request by pavel-kirienko**
This is an implementation and a demonstration in support of https://github.com/UAVCAN/public_regulated_data_types/pull/109.

Instead of specifying the port-ID explicitly when instantiating a port: `node.presentation.make_publisher(Type, 1234)`
Now, one uses indirection to source the port-ID from the registry: `node.make_publisher(Type, 'my_subject')`
The new node factory `make_node()` removes boilerplate and hard-coded identifiers.

Please find the documentation for this change on the readthedocs PR build site:

- https://pyuavcan--154.org.readthedocs.build/en/154/pages/demo.html
- https://pyuavcan--154.org.readthedocs.build/en/154/api/pyuavcan.application.html#module-pyuavcan.application

It would be super if one could follow the tutorial along to make sure that it doesn't omit any crucial details. If you do that, note that you will need to install Yakut from a branch for now (I will merge/release it immediately after this PR is accepted):

    pip install git+https://github.com/UAVCAN/yakut@orc

I do not recommend reviewing the code because our limited resources are better spent on more important things.

### CODE REVIEW

**Comment by davidlenfesty** [comment]
I was trying to work through this and found a bug with the DSDL generation:

```
pydsdl._error.InternalError: /tmp/pyuavcan_demo/public_regulated_data_types/uavcan/diagnostic/8184.Record.1.1.uavcan:4: Conflicting definitions: [DSDLDefinition(full_name='uavcan.time.SynchronizedTimestamp', version=Version(major=1, minor=0), fixed_port_id=None, file_path='/tmp/pyuavcan_demo/public_regulated_data_types/uavcan/time/SynchronizedTimestamp.1.0.uavcan'), DSDLDefinition(full_name='uavcan.time.SynchronizedTimestamp', version=Version(major=1, minor=0), fixed_port_id=None, file_path='/tmp/pyuavcan_demo/public_regulated_data_types/uavcan/time/SynchronizedTimestamp.1.0.uavcan')]
```

I get this when running `yakut compile public_regulated_data/uavcan` on the `master` branch with the version of yakut you specified (not when running it with 0.1.5). It seems to come from this branch of pyuavcan but I haven't *fully* verified that.

**Comment by pavel-kirienko** [comment]
It was fixed about one month ago: https://github.com/UAVCAN/pydsdl/pull/61

Please make sure you are running the latest PyDSDL: `pip install -U pydsdl`. I guess we should bump the minimal required version in Nunavut.

**Comment by davidlenfesty** [comment]
Okay with updated dependancies (python package management is just a joy...) I got everything to run well, except for orchestration but I'm assuming that's not important to this PR, and don't have too much time to play with this.

One nit is that the demo app's filename should probably be specified immediately prior to the code, the snippet given in "Running the Application" is the first reference to the filename used for the demo.

**Comment by pavel-kirienko** [comment]
> I got everything to run well, except for orchestration but I'm assuming that's not important to this PR

The directory removal problem should be fixed now but you are right, this is not that important.

Do you think such register integration can be implemented in uavcan.rs?

**Comment by davidlenfesty** [comment]
> Do you think such register integration can be implemented in uavcan.rs?

Yep, although I don't plan on implementing it where I am currently working (which is roughly equivalent to the presentation layer in pyuavcan). I want the core `uavcan-rs` crate to be as general and cross-platform as possible.

A user-friendly "application" crate on top of the core crate would likely be what I would want to work on after I hit 1.0, and register integration is definitely a natural feature to add there.

**Comment by pavel-kirienko** [comment]
> A user-friendly "application" crate on top of the core crate would likely be what I would want to work on after I hit 1.0, and register integration is definitely a natural feature to add there.

Okay. I think it's critical though to make the application crate no-std as well. We don't want embedded developers to reinvent this wheel.

**Comment by thirtytwobits** [comment]
- [ ]  Provide a step-by-step set of instructions for setting up the proper directory structure for the demo.
- [ ] Move the "Just-in-time vs. ahead-of-time DSDL compilation" section to after "running the application section"
- [ ] start with a sentence or two about what the demo is demonstrating. 
- [ ] Print a message from the demo that says "running. ctrl+c to exit"
- [ ] The section on Yakut; it's not clear that the examples are all to be run as separate processes. Perhaps you should be explicit about the number of shells. Something like "in addition to the terminal running pyuavcan open four more sessions and start the following yakut listeners..."

**Comment by thirtytwobits** [comment]
Startup sometimes throws:
```
"Available registers do not encode a valid transport configuration: ['uavcan.can.bitrate', 'uavcan.can.iface', 'uavcan.can.mtu', 'uavcan.loopback', 'uavcan.node.description', 'uavcan.node.id', 'uavcan.node.unique_id', 'uavcan.serial.baudrate', 'uavcan.serial.duplicate_service_transfers', 'uavcan.serial.iface', 'uavcan.udp.duplicate_service_transfers', 'uavcan.udp.iface', 'uavcan.udp.mtu']"
  File "/nxp_linux/demo/demo.py", line 63, in __init__
    self._node = pyuavcan.application.make_node(node_info, DemoApp.REGISTER_FILE)
  File "/nxp_linux/demo/demo.py", line 169, in <module>
    app = DemoApp()
```

**Comment by pavel-kirienko** [comment]
>Startup sometimes throws:

It is supposed to do that when you run the application for the first time (i.e., the database file is not yet created) without exporting environment variables. Can you confirm that it happens after you export the variables?

>Can we make this into a config file that is read into the demo app?

Kind of like this one? https://github.com/pavel-kirienko/yukon/blob/master/test.orc.yaml

In a way, that's what the last part of the tutorial is about.

**Comment by thirtytwobits** [comment]
```
$ yakut orc launch.orc.yaml
/bin/sh: 1: ncat: not found
2021-03-05 04:21:13 0031371 WAR yakut.cmd.orchestrate: Call stack: 'launch.orc.yaml' $ 6 ? 0
PID=00031396 Stopping (was started 0.0 sec ago)
2021-03-05 04:21:13 0031371 WAR yakut.cmd.orchestrate: Call stack: 'launch.orc.yaml' $ 2 $ 0
PID=00031384 Stopping (was started 0.1 sec ago)
2021-03-05 04:21:13 0031371 WAR yakut.cmd.orchestrate: Call stack: 'launch.orc.yaml' $ 3
PID=00031387 Stopping (was started 0.1 sec ago)
2021-03-05 04:21:13 0031371 WAR yakut.cmd.orchestrate: Call stack: 'launch.orc.yaml' $ 4
PID=00031390 Stopping (was started 0.1 sec ago)
Traceback (most recent call last):
  File "/nxp_linux/demo/.penv/bin/yakut", line 5, in <module>
    from yakut import main
  File "/nxp_linux/demo/.penv/lib/python3.7/site-packages/yakut/__init__.py", line 15, in <module>
    from .main import main as main, subcommand as subcommand, Purser as Purser, pass_purser as pass_purser
  File "/nxp_linux/demo/.penv/lib/python3.7/site-packages/yakut/main.py", line 13, in <module>
    from yakut.param.transport import transport_factory_option, TransportFactory, Transport
  File "/nxp_linux/demo/.penv/lib/python3.7/site-packages/yakut/param/transport.py", line 9, in <module>
    import pyuavcan
  File "/nxp_linux/demo/.penv/lib/python3.7/site-packages/pyuavcan/__init__.py", line 72, in <module>
    import pyuavcan.dsdl as dsdl  # pylint: disable=wrong-import-position  # noqa
  File "/nxp_linux/demo/.penv/lib/python3.7/site-packages/pyuavcan/dsdl/__init__.py", line 25, in <module>
    from ._compiler import compile as compile  # pylint: disable=redefined-builtin
  File "/nxp_linux/demo/.penv/lib/python3.7/site-packages/pyuavcan/dsdl/_compiler.py", line 17, in <module>
    import pydsdl
  File "/nxp_linux/demo/.penv/lib/python3.7/site-packages/pydsdl/__init__.py", line 25, in <module>
    from ._namespace import read_namespace as read_namespace                            # noqa
  File "/nxp_linux/demo/.penv/lib/python3.7/site-packages/pydsdl/_namespace.py", line 12, in <module>
    from . import _dsdl_definition
  File "/nxp_linux/demo/.penv/lib/python3.7/site-packages/pydsdl/_dsdl_definition.py", line 12, in <module>
Traceback (most recent call last):
    from . import _parser
  File "/nxp_linux/demo/.penv/lib/python3.7/site-packages/pydsdl/_parser.py", line 127, in <module>
  File "/nxp_linux/demo/.penv/bin/yakut", line 5, in <module>
    class _ParseTreeProcessor(parsimonious.NodeVisitor):
  File "/nxp_linux/demo/.penv/lib/python3.7/site-packages/pydsdl/_parser.py", line 139, in _ParseTreeProcessor
    grammar = parsimonious.Grammar(_grammar_file.read())  # type: ignore
  File "/nxp_linux/demo/.penv/lib/python3.7/site-packages/pydsdl/third_party/parsimonious/grammar.py", line 69, in __init__
    from yakut import main
  File "/nxp_linux/demo/.penv/lib/python3.7/site-packages/yakut/__init__.py", line 15, in <module>
    exprs, first = self._expressions_from_rules(rules, decorated_custom_rules)
  File "/nxp_linux/demo/.penv/lib/python3.7/site-packages/pydsdl/third_party/parsimonious/grammar.py", line 105, in _expressions_from_rules
    tree = rule_grammar.parse(rules)
  File "/nxp_linux/demo/.penv/lib/python3.7/site-packages/pydsdl/third_party/parsimonious/grammar.py", line 115, in parse
    return self.default_rule.parse(text, pos=pos)
  File "/nxp_linux/demo/.penv/lib/python3.7/site-packages/pydsdl/third_party/parsimonious/expressions.py", line 120, in parse
    node = self.match(text, pos=pos)
  File "/nxp_linux/demo/.penv/lib/python3.7/site-packages/pydsdl/third_party/parsimonious/expressions.py", line 135, in match
    node = self.match_core(text, pos, {}, error)
  File "/nxp_linux/demo/.penv/lib/python3.7/site-packages/pydsdl/third_party/parsimonious/expressions.py", line 178, in match_core
    error)
  File "/nxp_linux/demo/.penv/lib/python3.7/site-packages/pydsdl/third_party/parsimonious/expressions.py", line 333, in _uncached_match
    node = m.match_core(text, new_pos, cache, error)
  File "/nxp_linux/demo/.penv/lib/python3.7/site-packages/pydsdl/third_party/parsimonious/expressions.py", line 178, in match_core
    error)
  File "/nxp_linux/demo/.penv/lib/python3.7/site-packages/pydsdl/third_party/parsimonious/expressions.py", line 427, in _uncached_match
    node = self.members[0].match_core(text, new_pos, cache, error)
  File "/nxp_linux/demo/.penv/lib/python3.7/site-packages/pydsdl/third_party/parsimonious/expressions.py", line 178, in match_core
    error)
  File "/nxp_linux/demo/.penv/lib/python3.7/site-packages/pydsdl/third_party/parsimonious/expressions.py", line 333, in _uncached_match
    node = m.match_core(text, new_pos, cache, error)
  File "/nxp_linux/demo/.penv/lib/python3.7/site-packages/pydsdl/third_party/parsimonious/expressions.py", line 178, in match_core
    error)
  File "/nxp_linux/demo/.penv/lib/python3.7/site-packages/pydsdl/third_party/parsimonious/expressions.py", line 356, in _uncached_match
    node = m.match_core(text, pos, cache, error)
  File "/nxp_linux/demo/.penv/lib/python3.7/site-packages/pydsdl/third_party/parsimonious/expressions.py", line 178, in match_core
    error)
  File "/nxp_linux/demo/.penv/lib/python3.7/site-packages/pydsdl/third_party/parsimonious/expressions.py", line 333, in _uncached_match
    node = m.match_core(text, new_pos, cache, error)
  File "/nxp_linux/demo/.penv/lib/python3.7/site-packages/pydsdl/third_party/parsimonious/expressions.py", line 178, in match_core
    error)
  File "/nxp_linux/demo/.penv/lib/python3.7/site-packages/pydsdl/third_party/parsimonious/expressions.py", line 458, in _uncached_match
    node = self.members[0].match_core(text, new_pos, cache, error)
  File "/nxp_linux/demo/.penv/lib/python3.7/site-packages/pydsdl/third_party/parsimonious/expressions.py", line 178, in match_core
    error)
  File "/nxp_linux/demo/.penv/lib/python3.7/site-packages/pydsdl/third_party/parsimonious/expressions.py", line 356, in _uncached_match
    node = m.match_core(text, pos, cache, error)
  File "/nxp_linux/demo/.penv/lib/python3.7/site-packages/pydsdl/third_party/parsimonious/expressions.py", line 178, in match_core
    error)
  File "/nxp_linux/demo/.penv/lib/python3.7/site-packages/pydsdl/third_party/parsimonious/expressions.py", line 333, in _uncached_match
    node = m.match_core(text, new_pos, cache, error)
  File "/nxp_linux/demo/.penv/lib/python3.7/site-packages/pydsdl/third_party/parsimonious/expressions.py", line 178, in match_core
    error)
  File "/nxp_linux/demo/.penv/lib/python3.7/site-packages/pydsdl/third_party/parsimonious/expressions.py", line 333, in _uncached_match
    node = m.match_core(text, new_pos, cache, error)
  File "/nxp_linux/demo/.penv/lib/python3.7/site-packages/pydsdl/third_party/parsimonious/expressions.py", line 178, in match_core
    error)
  File "/nxp_linux/demo/.penv/lib/python3.7/site-packages/pydsdl/third_party/parsimonious/expressions.py", line 279, in _uncached_match
    m = self.re.match(text, pos)
KeyboardInterrupt
    from .main import main as main, subcommand as subcommand, Purser as Purser, pass_purser as pass_purser
  File "/nxp_linux/demo/.penv/lib/python3.7/site-packages/yakut/main.py", line 13, in <module>
    from yakut.param.transport import transport_factory_option, TransportFactory, Transport
  File "/nxp_linux/demo/.penv/lib/python3.7/site-packages/yakut/param/transport.py", line 9, in <module>
    import pyuavcan
  File "/nxp_linux/demo/.penv/lib/python3.7/site-packages/pyuavcan/__init__.py", line 72, in <module>
    import pyuavcan.dsdl as dsdl  # pylint: disable=wrong-import-position  # noqa
  File "/nxp_linux/demo/.penv/lib/python3.7/site-packages/pyuavcan/dsdl/__init__.py", line 29, in <module>
    from ._composite_object import serialize as serialize
  File "/nxp_linux/demo/.penv/lib/python3.7/site-packages/pyuavcan/dsdl/_composite_object.py", line 16, in <module>
    from . import _serialized_representation
  File "/nxp_linux/demo/.penv/lib/python3.7/site-packages/pyuavcan/dsdl/_serialized_representation/__init__.py", line 6, in <module>
    from ._serializer import Serializer as Serializer
  File "/nxp_linux/demo/.penv/lib/python3.7/site-packages/pyuavcan/dsdl/_serialized_representation/_serializer.py", line 11, in <module>
    import numpy
  File "/nxp_linux/demo/.penv/lib/python3.7/site-packages/numpy/__init__.py", line 143, in <module>
    from . import lib
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
```

**Comment by thirtytwobits** [comment]
> Can you confirm that it happens after you export the variables?

Yeah. The ports and the IP coming from a config file would make this demo so much better.

**Comment by pavel-kirienko** [comment]
@thirtytwobits check out my latest changes. I think I addressed everything except:

> the environment variables for the port identifiers is clunky. Can we make this into a config file that is read into the demo app? This also makes it WAY easier to debug.

This is not really meant to be very human-friendly. I think it makes sense to start with the basics even if they are not particularly convenient and then gradually introduce more advanced matters like the orchestrator. The orchestration file is essentially the config file you are looking for, but if we introduce it from the start it may get confusing.

> Log a warning from demo_app.py if the file is not called demo_app.py since the orc-file part of the tutorial will fail with a big ol' stack trace if you don't adhere to this convention.

I addressed this by making the demo easier to follow along step-by-step such that by the time the reader gets to the orchestrator the file should already be created. I also added another hint about this right after the orchestration script for good measure.

> yakut pub --count 10 2345:uavcan.si.unit.temperature.Scalar.1.0 'kelvin: 250' ... example doesn't work (nothing is printed by yakut sub -M 2347:uavcan.si.unit.voltage.Scalar.1.0

Not reproducible, neither locally nor in CI.

**Review by thirtytwobits — APPROVED** [review]
SO much better now! Thanks Pavel.

**Pull request merged**
