### PR TITLE
fix off-by-one error in union tag and array length bit size computation

### PR DESCRIPTION
**Pull request by jschall**

### CODE REVIEW

**Comment by pavel-kirienko** [comment]
Thanks, @jschall! Nice catch. Could you please also fix the unit tests?

**Comment by pavel-kirienko** [comment]
Hey @jschall, nudge nudge!

**Comment by jschall** [comment]
I will try to get to this tomorrow.

**Comment by mkeeter** [comment]
I think that the fix to `union_tag_bits` may be incorrect: a union with two elements only needs 1 bit to identify which one is selected, so it should be `ceil(log2(num_elements))` as before.

The `+ 1` is only necessary for dynamic arrays, e.g. an array with `<=64` elements actually has 65 possible sizes (0, 1, 2, ... 64).

**Comment by pavel-kirienko** [comment]
> I think that the fix to `union_tag_bits` may be incorrect: a union with two elements only needs 1 bit to identify which one is selected, so it should be `ceil(log2(num_elements))` as before.

This is true.

> The `+ 1` is only necessary for dynamic arrays, e.g. an array with `<=64` elements actually has 65 possible sizes (0, 1, 2, ... 64).

Of course, static arrays do not have a length field at all.

**Comment by pavel-kirienko** [comment]
@jschall

**Comment by jschall** [comment]
Done.

**Pull request merged**
